### ISSUE TITLE
Example config with setting sync

### ISSUE THREAD

**Issue by saileshbro** [cyberbiont/vscode-profiles#2]
Hey, great extension.
Can you create an example showing how to sync with setting sync? We can natively sync with vscode without using `setting-sync` extension now.

**Comment by cyberbiont** [comment]
Hi. thank you!

The problem with native VS Code setting-sync is that it does not support multiple profiles. So you can backup / sync only one extensions set at a time, and while you are switching your profiles in vscode-profiles, your cloud backups will overwrite each other.
On the other hand, old settings-sync extension stores your backups in a Github gist, so you can create as many of them as you want, and set them to correspond each of your profiles.

Actually, the setup is quite simple, please refer to this (section)[https://github.com/cyberbiont/vscode-profiles#integration-with-other-extensions] in README.
After you create a new profile, you should also create a new gist via settings-sync extension and add this gist's id under '"sync.gist" field in your profile configuration. Since the profile configurations are stored as `settings-cycler` settings blocks and are switched automatically when you switch profiles,  `Sync:Update` command will know the correct gist id to sync your profile with, when the profile is active.

I think the section in README explains is it, but if you have more questions, please be more specific what problems you are having with this setup.

**Comment by saileshbro** [comment]
@cyberbiont I see with `settings-sync` we can store the config in different Github Gists. This is a great extension to manage extensions. Thanks

**Comment by cyberbiont** [comment]
Feel free to ask in case you have more questions
