### ISSUE TITLE
Sharing environments globally?

### ISSUE THREAD

**Issue by Anselmoo** [cyberbiont/vscode-profiles#9]
Is there a chance to share the dedicated environments globally between different VS-editors?

Thx

**Comment by cyberbiont** [comment]
Hi! Not sure what you mean.
Only one profile can be active at the same time,  so if you have several VSCode instances open,    once you reload them, the same profle will be applied (it comes from the fact that vscode reads extensions from the single folder). Until the reload,  however,  the old extensions set will remain,  since it is already loaded in memory,  but this situation can potentionally lead to errors so always reload all windows on profile change.

**Comment by Anselmoo** [comment]
@cyberbiont thx for the response:

I want to know if I the environment with the name `RUST` will be synchronized with the visual code editor on a different platform. It would be nice if it is possible?

**Comment by cyberbiont** [comment]
Yes,  you can do this using SettingsSync extension. Please refer to the corresponding chapter in Readme on how to setup vscode-profles with settingssync.

**Comment by Anselmoo** [comment]
Thx a lot!!
